---
kind: pipeline
type: exec
name: fixe

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    commands:
      - hostname
node:
    instance: fixe_exec_amd64_runner

---
kind: pipeline
type: exec
name: ca

platform:
  os: linux
  arch: amd64

steps:
  - name: ca
    commands:
      - hostname

node:
    instance: ca_exec_amd64_runner

---
kind: pipeline
type: exec
name: fr

platform:
  os: linux
  arch: amd64

steps:
  - name: fr
    commands:
      - hostname

node:
    instance: fr_exec_amd64_runner

