---
kind: pipeline
type: exec
name: fixe

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    commands:
      - hostname
node:
    node: fixe

---
kind: pipeline
type: exec
name: ca

platform:
  os: linux
  arch: amd64

steps:
  - name: ca
    commands:
      - hostname

node:
    node: ca
---
kind: pipeline
type: exec
name: fr

platform:
  os: linux
  arch: amd64

steps:
  - name: fr
    commands:
      - hostname

node:
    node: fr

